config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'pages/dashboard', to: 'pages#dashboard'
  # resources :pages, only: %i[dashboard home]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :spaceships, except: [:index] do
    resources :bookings, only: %i[create edit update]
    resources :spaceship_tags, only: %i[create]
  end

  resources :bookings, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :spaceship_tags, dependent: :destroy
  has_many :tags, through: :spaceship_tags

  
  def unavailable_dates
    bookings.pluck(:start_date, :end_date, :id).map do |date|
      { from: date[0], to: date[1], booking_id: date[2] }
    end
  end

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :color, :seats, :year, :address, :price ],
  associated_against: {
    user: [ :first_name, :last_name ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/spaceship_tag.rb
  class SpaceshipTag < ApplicationRecord
  belongs_to :spaceship
  belongs_to :tag
  end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :spaceship_tags, dependent: :destroy
  has_many :spaceships, through: :spaceship_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spaceships, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :spaceships, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :select_spaceship, only: %i[new create edit]
  before_action :select_booking, only: %i[edit update destroy]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.spaceship = @spaceship
    @booking.user = current_user
    if @booking.save
      redirect_to pages_dashboard_path
    else
      render 'spaceships/show', status: :unprocessable_entity
    end
  end

  def edit
    @unavailable_dates = @spaceship.unavailable_dates
    @unavailable_dates.delete_if { |h| h[:booking_id] == params[:id].to_i }
  end

  def update
    if @booking.update(booking_params)
      redirect_to pages_dashboard_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to pages_dashboard_path
  end

  private

  def select_spaceship
    @spaceship = Spaceship.find(params[:spaceship_id])
  end

  def select_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @spaceships = Spaceship.all
    @spaceships_map = Spaceship.geocoded
    @markers = @spaceships_map.map do |spaceship|
      {
        lat: spaceship.latitude,
        lng: spaceship.longitude,
        info_window_html: render_to_string(partial: "spaceships/info_window", locals: {spaceship: spaceship}),
        marker_html: render_to_string(partial: "spaceships/marker", locals: {spaceship: spaceship})
      }
    end
    if params[:query].present?
      sql_subquery = <<~SQL
        spaceships.name @@ :query
        OR spaceships.color @@ :query
        OR spaceships.seats @@ :query
        OR spaceships.year @@ :query
        OR spaceships.address @@ :query
        OR users.first_name @@ :query
        OR users.last_name @@ :query
      SQL
      @spaceships = @spaceships.global_search(params[:query])
    end
  end

  def dashboard
    @current_user_bookings = current_user.bookings.order(:start_date)
    @current_user_spaceships = current_user.spaceships
    # @current_user_spaceships = Spaceship.all
  end
end

app/controllers/spaceship_tags_controller.rb
class SpaceshipTagsController < ApplicationController
  def create
    @spaceship = Spaceship.find(params[:spaceship_id])
    @tags = Tag.where(id: params.dig(:spaceship_tag, :tag))
    @tags.each do |tag|
      spaceship_tag = SpaceshipTag.new(spaceship: @spaceship, tag: tag)
      spaceship_tag.save
    end
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_spaceship, only: %i[show edit update destroy]

  def index
    @spaceships = Spaceship.all
    if params[:query].present?
      sql_subquery = <<~SQL
        spaceships.name @@ :query
        OR spaceships.color @@ :query
        OR spaceships.seats @@ :query
        OR spaceships.year @@ :query
        OR spaceships.address @@ :query
        OR users.first_name @@ :query
        OR users.last_name @@ :query
      SQL
      @spaceships = @spaceships.global_search(params[:query])
    end
  end

  def new
    @spaceship = Spaceship.new
  end

  def show
    @spaceships = Spaceship.geocoded
    @markers = @spaceships.where(id: params[:id]).map do |spaceship|
      {
        lat: spaceship.latitude,
        lng: spaceship.longitude,
        info_window_html: render_to_string(partial: "spaceships/info_window", locals: {spaceship: spaceship}),
        marker_html: render_to_string(partial: "spaceships/marker", locals: {spaceship: spaceship})
      }
    end
    @booking = Booking.new
    @unavailable_dates = @spaceship.unavailable_dates
  end

  def create
    @spaceship_tag = SpaceshipTag.new
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    save_changes
  end

  def edit
    @spaceship_tag = SpaceshipTag.new
  end

  def destroy
    @spaceship.destroy
    redirect_to pages_dashboard_path
  end

  def update

    params[:spaceship][:tags].each { |tag| SpaceshipTag.create(spaceship: @spaceship, tag_id: tag) }

    @spaceship.update(spaceship_params)
    save_changes
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :color, :seats, :year, :description, :photo, :address)
  end

  def set_spaceship
    @spaceship = Spaceship.find(params[:id])
  end

  def save_changes
    if @spaceship.save
      redirect_to spaceship_path(@spaceship)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
    end

    def resource
    @resource ||= User.new
    end

    def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
    end
end

app/views/bookings/edit.html.erb
<%= render "/pages/navbardark" %>

<div class="container mt-3">
  <div class="row justify-content-center">
  <div class="col-6 mb-3 form-inline" >
    <%= render "spaceships/booking_form"%>
  </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
  <div class="col-6 mb-3 form-inline" >
    <%= simple_form_for([ @spaceship, @booking]) do |f| %>
      <%= f.input :start_date, as: :date %>
      <%= f.input :end_date, as: :date %>
      <p> Price:  </p>

      <div class="col-9 d-flex">
        <p class="form-control col-6 flex-grow-1">$120</p>
        <%= f.submit "New booking", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacex</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/_bookingcard.html.erb
<%= link_to spaceship_path(booking.spaceship), class: 'text-decoration-none text-white' do %>
  <% if booking.spaceship.photo.attached?  %>
  <%= cl_image_tag(booking.spaceship.photo.key, crop: :fit, width: 250) %>
  <% else %>
    <%= image_tag('spaceship.jpeg') %>
  <% end %>
  <h3 class="text-wrap mb-3"><%= booking.spaceship.name %></h3>
  <i class="fa-solid fa-paint-roller mb-1"> <%= booking.spaceship.color %></i>
  <i class="fa-solid fa-chair mb-1"> <%= booking.spaceship.seats %></i>
  <i class="fa-regular fa-calendar-days mb-1"> <%= booking.spaceship.year %></i>
  <p class="card-text"><span class="fw-bold text-muted">booked:</span> <%= booking.start_date %> - <%= booking.end_date %></p>
  <p class="card-text"><span class="fw-bold text-muted">price:</span> £<%= booking.spaceship.price %></p>
  <%= link_to edit_spaceship_booking_path(booking.spaceship, booking), class: 'btn btn-primary position-absolute bottom-0 start-0 m-2' do %>
    <i class="fa-solid fa-pencil pe-1" style="color: #ffffff;"></i> Edit
  <% end %>
  <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger text-white position-absolute bottom-0 end-0 m-2' do %>
   <i class="fa-regular fa-trash-can pe-1" style="color: #ffffff;"></i> Delete
   <% end %>
 <% end %>

app/views/pages/_card_map.html.erb
<div>
  <div class="row">
    <div class="col-md-8">
        <div class="container mb-3">

          <div class="d-flex flex-wrap gap-3 justify-content-center">
            <%@spaceships.each do |spaceship| %>
              <%= link_to spaceship_path(spaceship), class: 'text-decoration-none', style: "width: 250px; " do %>
                <div class="text-white card col-4 pb-1 w-auto">
                  <%= render "indexcard", spaceship: spaceship %>
                  <div class="text-truncate mx-auto py-1 px-2 text-center w-100">
                  <i class="fa-solid fa-earth-asia"></i>
                    <%= spaceship.address %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>

    <div class="col-md-4">
      <div id="map" style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>

</div>

app/views/pages/_dashboardcard.html.erb
<%= link_to spaceship_path(spaceship), class: 'text-decoration-none text-white' do %>
  <% if spaceship.photo.attached?  %>
    <%= cl_image_tag(spaceship.photo.key,:width => 270, :height => 350, crop: :fit) %>
  <% else %>
    <%= image_tag('spaceship.jpeg', :height => 250) %>
  <% end %>

  <h3 class="text-wrap mt-3"> <%= spaceship.name %></h3>
  <p class="card-text text-truncate text-wrap "><%= spaceship.description.truncate(27, separator: ' ') %></p>
  <i class="fa-solid fa-paint-roller mb-1">  <%= spaceship.color %></i>
  <i class="fa-solid fa-chair mb-1">  <%= spaceship.seats %></i>
  <i class="fa-regular fa-calendar-days mb-1"> <%= spaceship.year %></i>
  <i class="fa-solid fa-dollar-sign">  <%= spaceship.price %></i>
  <%= link_to '', class: 'invisible' %>
 <% end %>

app/views/pages/_indexcard.html.erb
<%# only fit homepage-img %>
<div style="max-width: 100%; object-fit: cover;
        width: 250; height: 150px;
        overflow: hidden; align-items: center; display: flex; justify-content: center; align-items: center;">
  <% if spaceship.photo.attached?  %>
      <%= cl_image_tag(spaceship.photo.key,:width =>370, crop: :fit) %>
  <% else %>
    <%= image_tag('spaceship.jpeg', :height => 150, width: 260 ) %>
  <% end %>
</div>

<h5 class="text-wrap mb-2 mt-3 mx-auto"><%= spaceship.name.truncate(27, separator: ' ') %></h5>
<div class="d-flex gap-1 mx-1 align-items-center justify-content-evenly">
  <i class="fa-solid fa-euro-sign mb-1 text-center p-2 shadow"> <%= spaceship.price %></i>
  <i class="fa-solid fa-chair mb-1 text-center p-2 shadow"> <%= spaceship.seats %></i>
  <i class="fa-regular fa-calendar-days mb-1 text-center p-2 shadow"> <%= spaceship.year %></i>
</div>

app/views/pages/_menu.html.erb
<div data-controller="dashboard" class="menu">
  <div class="container p-4">
  <h4>My bookings</h4>
  <ul>
    <% @current_user_bookings.each do |booking| %>
      <button class="" data-action="click->dashboard#fire" ><%= booking.spaceship.name%></button>
    <% end %>
  </ul>
  <div class="menu-separator"><p>-</p></div>
  <h4>My spaceships</h4>
  <ul>
    <% @current_user_spaceships.each do |spaceship| %>
      <%= link_to spaceship.name, spaceship_path(spaceship), class: 'link' %>
    <% end %>
  </ul>
  </div>

</div>

app/views/pages/_nav_home.html.erb
<div id="dark" class="navbar sticky-top navbar-expand-sm">
    <div class="container-fluid">

      <div>
        <%= link_to root_path, class: 'd-flex align-items-center gap-3 linktext text-decoration-none text-home' do %>
          <i class="fa-solid fa-shuttle-space mx-1"></i> <h4 class="m-0">Spacex</h4>
          <% end %>
      </div>

      <div><%= render 'pages/search_bar' %></div>

      <div class="d-flex align-items-center text-center gap-3">
        <div class="border rounded-pill py-1">
          <%= link_to "Add your Spaceship", new_spaceship_path, class: 'linktext text-decoration-none px-3' %>
        </div>
        <% if user_signed_in? %>
          <div class="border rounded-pill py-1">
            <%= link_to 'Dashboard', pages_dashboard_path, class: 'linktext text-decoration-none px-3' %>
          </div>
          <div>Hello, <%= current_user.first_name %>!</div>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-decoration-none btn btn-success' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'text-decoration-none', class: 'text-decoration-none btn btn-success' %>
        <% end %>
      </div>

    </div>
  </div>

app/views/pages/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm">
    <div class="container-fluid">

      <div>
        <%= link_to root_path, class: 'd-flex align-items-center gap-2 text-decoration-none' do %>
          <i class="fa-solid fa-shuttle-space mx-1"></i> <h3 class="m-0">SpaceX</h3>
          <% end %>
      </div>

      <div class="d-flex align-items-center text-center gap-3">
        <div class="border rounded-pill py-1">
          <%= link_to "Add your Spaceship", new_spaceship_path, class: 'linktext text-decoration-none px-3', style: 'color: #3E1F47;' %>
        </div>
        <% if user_signed_in? %>
          <div class="border rounded-pill py-1">
            <%= link_to 'Dashboard', pages_dashboard_path, class: 'linktext text-decoration-none px-3', style: 'color: #3E1F47;'  %>
          </div>
          <div>Hello, <%= current_user.first_name %>!</div>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-decoration-none btn btn-success' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'text-decoration-none', class: 'text-decoration-none btn btn-success' %>
        <% end %>
      </div>

    </div>
  </div>

app/views/pages/_navbardark.html.erb
<div id="dark" class="navbar sticky-top navbar-expand-sm">
    <div class="container-fluid">

      <div>
        <%= link_to root_path, class: 'd-flex align-items-center gap-3 linktext text-decoration-none text-home' do %>
          <i class="fa-solid fa-shuttle-space mx-1"></i> <h4 class="m-0">SpaceX</h4>
          <% end %>
      </div>


      <div class="d-flex align-items-center text-center gap-3">
        <div class="border rounded-pill p-1">
          <%= link_to "Add your Spaceship", new_spaceship_path, class: 'linktext text-decoration-none px-3' %>
        </div>
        <% if user_signed_in? %>
          <div class="border rounded-pill p-1">
            <%= link_to 'Dashboard', pages_dashboard_path, class: 'linktext text-decoration-none px-3' %>
          </div>
          <div>Hello, <%= current_user.first_name %>!</div>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-decoration-none btn btn-success' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'text-decoration-none', class: 'text-decoration-none btn btn-success' %>
        <% end %>
      </div>

    </div>
  </div>

app/views/pages/_search_bar.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
        %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<%= render "/pages/navbardark" %>

<div class="d-flex" data-controller="dashboard">
  <div><div class="menu">
  <div class="container p-4">
  <button class="link btn btn-primary" data-action="click->dashboard#fire"><h4>My bookings</h4></button>
  <ul>
    <% @current_user_bookings.each do |booking| %>
      <li><%= link_to booking.spaceship.name, spaceship_path(booking.spaceship), class: 'link'%></li>
    <% end %>
  </ul>
  <div class="menu-separator"><p>-</p></div>
  <button class="link btn btn-primary" data-action="click->dashboard#fire"><h4>My spaceships</h4></button>
  <ul>
    <% @current_user_spaceships.each do |spaceship| %>
      <%= link_to spaceship.name, spaceship_path(spaceship), class: 'link' %>
    <% end %>
  </ul>
  </div>

</div> </div>

  <div>

    <div class="individualdisplay mt-3" data-dashboard-target="booking">
      <% @current_user_bookings.each do |booking| %>
        <div class="dashboard-individual m-4">
          <div class="d-flex m-5">
            <div class="photo">
              <% if booking.spaceship.photo.attached?  %>
              <%= cl_image_tag(booking.spaceship.photo.key, crop: :fit, width: 450) %>
              <% else %>
                <%= image_tag('spaceship.jpeg') %>
              <% end %>
            </div>

            <div class="title m-5">
              <h3 class="text-wrap mb-3"><%= booking.spaceship.name %></h3>
              <i class="fa-solid fa-paint-roller mb-1"> <%= booking.spaceship.color %></i>
              <i class="fa-solid fa-chair mb-1"> <%= booking.spaceship.seats %></i>
              <i class="fa-regular fa-calendar-days mb-1"> <%= booking.spaceship.year %></i>
              <div class="booking mt-5">
                <p class="text">Booked: <%= booking.start_date %> / <%= booking.end_date %></p>
              </div>
            </div>

            <div class="description m-5">
              <p><%= booking.spaceship.description %></p>
              <div>
                <%= link_to edit_spaceship_booking_path(booking.spaceship, booking), class: 'btn btn-primary my-2' do %>
                  <i class="fa-solid fa-pencil pe-1" style="color: #ffffff;">  Edit</i>
                <% end %>
                <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' do %>
                  <i class="fa-regular fa-trash-can pe-1" style="color: #ffffff;">  Delete</i>
                <% end %>
              </div>
            </div>

          </div>

        </div>
     <% end %>
    </div>



    <div class="individualdisplay mt-3 d-none" data-dashboard-target="spaceship">
      <% @current_user_spaceships.each do |spaceship| %>
        <div class="dashboard-spaceship m-4">
          <div class="d-flex m-5">
            <div class="photo">
              <% if spaceship.photo.attached?  %>
              <%= cl_image_tag(spaceship.photo.key, crop: :fit, width: 450) %>
              <% else %>
                <%= image_tag('spaceship.jpeg') %>
              <% end %>
            </div>

            <div class="titles m-5">
              <h3 class="text-wrap mb-3"><%= spaceship.name %></h3>
              <i class="fa-solid fa-paint-roller mb-1"> <%= spaceship.color %></i>
              <i class="fa-solid fa-chair mb-1"> <%= spaceship.seats %></i>
              <i class="fa-regular fa-calendar-days mb-1"> <%= spaceship.year %></i>

            <div class="description m-5">
              <p><%= spaceship.description %></p>
            </div>

          </div>

        </div>
     <% end %>
    </div>

</div>

app/views/spaceships/_form.html.erb
<%= simple_form_for(spaceship) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="d-flex justify-content-center">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :color %>
      <%= f.input :seats %>
      <%= f.input :year %>
      <%= f.input :address %>
      <div>

      <%= f.input :tags, collection: Tag.all, input_html: {multiple: true, placeholder: "Select a tag", data: {controller: "tom-select", tom_select_options_value: {tags: true}}} %>

      </div>
      <%= f.input :description %>
      <%= f.file_field :photo %>
    </div>
  </div><br>

  <div class="d-flex justify-content-center">
    <div class="form-actions btn-primary d-flex justify-content-center">
      <%= f.button :submit, class: "btn btn-primary"%>
    </div>
    <div style="margin: 10px;"></div>
    <div class="d-flex justify-content-center">
      <%= link_to "Back to Homepage", spaceships_path, class:"btn btn-primary text-align-center"%>
    </div>
  </div>
<% end %>

app/views/spaceships/_info_window.html.erb
<h2><%= spaceship.name %></h2>
<p><%= spaceship.address %></p>

app/views/spaceships/_sign_in.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/spaceships/show.html.erb
<%= render "/pages/navbardark" %>

<div class="container" id="show-container">
  <div class="m-5">

    <div class="row align-items-center">

      <div class="col-4">
        <div id="show-image" style="text-align: left">
          <% if @spaceship.photo.attached?  %>
            <%= cl_image_tag(@spaceship.photo.key, :width => 500, :height => 400, crop: :fit) %>
          <% else %>
            <%= image_tag('spaceship.jpeg', :height => 250) %>
          <% end %>
        </div>
      </div>
        <div class="col-8 ">
        <h2 class="text-dark"><%= @spaceship.name %></h2>
        <div class="d-inline">
          <i class="fa-solid fa-paint-roller"> <%= @spaceship.color %></i>
          <i class="fa-solid fa-chair"> <%= @spaceship.seats %></i>
          <i class="fa-regular fa-calendar-days"> <%= @spaceship.year %></i>
        </div>
        <p class="position-relative mt-5"><h4 style="color: black;">About: </h4> <%= @spaceship.description %></p>
           <div class="card-tags">
            <% @spaceship.tags.each do |tag| %>
              <span class="badge"><%= tag.name %></span>
            <% end %>
          </div>


        <div>
          <% if user_signed_in? %>
            <% if current_user.id == @spaceship.user_id %>
              <%= link_to "Edit Spaceship", edit_spaceship_path(@spaceship), style: "text-decoration: none;" %><br>
              <%= link_to "Delete Spaceship", spaceship_path(@spaceship), style: "text-decoration: none;", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="col-4">
        <div>
          <h4 class="mt-4 mb-3">£ <%= @spaceship.price %> / Day</h4>
          <h5 class="mb-3">Owner: <%= @spaceship.user.first_name %> <%= @spaceship.user.last_name %></h5>
        </div>
      </div>
    </div>
        <div class="mt-4">
          <% if user_signed_in? %>
            <% if current_user.id != @spaceship.user_id %>
              <div data-controller="displaybookingform">
                <button class="btn btn-primary" data-action="click->displaybookingform#fire">Book</button>
                <div class="d-none" data-displaybookingform-target="form">
                  <% if user_signed_in? %>
                    <%= render "/spaceships/booking_form"%>
                  <% else %>
                    <%= render "/spaceships/sign_in" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>
            <p><strong>Want to book? You have to <%= link_to "sign in", new_user_session_path %></strong></p>
          <% end %>
        </div>
  </div>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>